defaults: &defaults
  image_host: http://admin.kidmeets.cn
  qiniu_bucket: kidmeets-images
  domain_name: http://kidsmeet.cn

development:
   <<: *defaults
   image_host: http://localhost:3000
   image_server: http://kidmeets-images.qiniudn.com

production:
   <<: *defaults
   image_host: http://admin.kidmeets.cn
   qiniu_bucket: kidmeets-images
   image_server: http://kidmeets-images.qiniudn.com


test:
   <<: *defaults
