defaults: &defaults
  image_host: http://admin.kidmeets.cn
  qiniu_bucket: kidmeets-images

development:
   <<: *defaults
   image_host: http://localhost:9292

production:
   <<: *defaults
   image_host: http://admin.kidmeets.cn
   qiniu_bucket: kidmeets-images

test:
   <<: *defaults